MLIR: lib/Conversion/ArmSVEToLLVM/ArmSVEToLLVM.cpp File Reference
ArmSVEToLLVM.cpp File Reference
#include "mlir/Conversion/ArmSVEToLLVM/ArmSVEToLLVM.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Dialect/ArmSVE/ArmSVEDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMArmSVEDialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/PatternMatch.h"
Classes
class ForwardOperands< OpTy >
class ReturnOpTypeConversion
Typedefs
using SdotOpLowering = OneToOneConvertToLLVMPattern< SdotOp, LLVM::aarch64_arm_sve_sdot >
using SmmlaOpLowering = OneToOneConvertToLLVMPattern< SmmlaOp, LLVM::aarch64_arm_sve_smmla >
using UdotOpLowering = OneToOneConvertToLLVMPattern< UdotOp, LLVM::aarch64_arm_sve_udot >
using UmmlaOpLowering = OneToOneConvertToLLVMPattern< UmmlaOp, LLVM::aarch64_arm_sve_ummla >
using VectorScaleOpLowering = OneToOneConvertToLLVMPattern< VectorScaleOp, LLVM::vector_scale >
Functions
static Type unwrap (Type type)
static Optional< Type > convertScalableVectorTypeToLLVM (ScalableVectorType svType, LLVMTypeConverter &converter)
static Optional< Value > addUnrealizedCast (OpBuilder &builder, ScalableVectorType svType, ValueRange inputs, Location loc)
Typedef Documentation
SdotOpLowering
using SdotOpLowering = OneToOneConvertToLLVMPattern<SdotOp, LLVM::aarch64_arm_sve_sdot>
Definition at line 24 of file ArmSVEToLLVM.cpp.
SmmlaOpLowering
using SmmlaOpLowering = OneToOneConvertToLLVMPattern<SmmlaOp, LLVM::aarch64_arm_sve_smmla>
Definition at line 27 of file ArmSVEToLLVM.cpp.
UdotOpLowering
using UdotOpLowering = OneToOneConvertToLLVMPattern<UdotOp, LLVM::aarch64_arm_sve_udot>
Definition at line 30 of file ArmSVEToLLVM.cpp.
UmmlaOpLowering
using UmmlaOpLowering = OneToOneConvertToLLVMPattern<UmmlaOp, LLVM::aarch64_arm_sve_ummla>
Definition at line 33 of file ArmSVEToLLVM.cpp.
VectorScaleOpLowering
using VectorScaleOpLowering = OneToOneConvertToLLVMPattern<VectorScaleOp, LLVM::vector_scale>
Definition at line 36 of file ArmSVEToLLVM.cpp.
Function Documentation
addUnrealizedCast()
static Optional<Value> addUnrealizedCast (OpBuilder & builder, ScalableVectorType svType, ValueRange inputs, Location loc) static
Definition at line 88 of file ArmSVEToLLVM.cpp.
References mlir::OpBuilder::create(), and mlir::ValueRange::getType().
Referenced by mlir::populateArmSVEToLLVMConversionPatterns().
convertScalableVectorTypeToLLVM()
static Optional<Type> convertScalableVectorTypeToLLVM (ScalableVectorType svType, LLVMTypeConverter & converter) static
Definition at line 50 of file ArmSVEToLLVM.cpp.
References mlir::TypeConverter::convertType(), elementType(), mlir::LLVM::LLVMScalableVectorType::get(), and unwrap().
Referenced by mlir::populateArmSVEToLLVMConversionPatterns().
unwrap()
static Type unwrap (Type type) static
Definition at line 39 of file ArmSVEToLLVM.cpp.
References mlir::emitError(), mlir::Type::getContext(), and mlir::LLVM::isCompatibleType().
Referenced by convertScalableVectorTypeToLLVM().