MLIR: lib/Dialect/AVX512/Transforms/LegalizeForLLVMExport.cpp File Reference
LegalizeForLLVMExport.cpp File Reference
#include "mlir/Dialect/AVX512/Transforms.h"
#include "mlir/Conversion/StandardToLLVM/ConvertStandardToLLVM.h"
#include "mlir/Dialect/AVX512/AVX512Dialect.h"
#include "mlir/Dialect/LLVMIR/LLVMDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/PatternMatch.h"
Functions
template<typename OpTy >
static Type getSrcVectorElementType (OpTy op)
Extracts the "main" vector element type from the given AVX512 operation.
template<>
Type getSrcVectorElementType (Vp2IntersectOp op)
Function Documentation
getSrcVectorElementType() [1/2]
template<typename OpTy > static Type getSrcVectorElementType (OpTy op) static
Extracts the "main" vector element type from the given AVX512 operation.
Definition at line 23 of file LegalizeForLLVMExport.cpp.
References getElementType().
getSrcVectorElementType() [2/2]
template<> Type getSrcVectorElementType (Vp2IntersectOp op)
Definition at line 27 of file LegalizeForLLVMExport.cpp.
References mlir::RewritePatternSet::add(), mlir::ConversionTarget::addIllegalOp(), mlir::ConversionTarget::addLegalOp(), mlir::OpBuilder::create(), elementType(), mlir::Pattern::getContext(), getElementType(), mlir::Type::getIntOrFloatBitWidth(), mlir::ConversionPattern::getTypeConverter(), mlir::Builder::getZeroAttr(), mlir::ConversionPatternRewriter::notifyMatchFailure(), mlir::LLVM::detail::oneToOneRewrite(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().