MLIR: lib/Dialect/Linalg/Transforms/Transforms.cpp File Reference
Transforms.cpp File Reference
#include "mlir/Dialect/Linalg/Transforms/Transforms.h"
#include "mlir/Dialect/Affine/Utils.h"
#include "mlir/Dialect/Linalg/Analysis/DependenceAnalysis.h"
#include "mlir/Dialect/Linalg/IR/LinalgOps.h"
#include "mlir/Dialect/Linalg/Utils/Utils.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/EDSC/Intrinsics.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/Matchers.h"
#include "mlir/Pass/Pass.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
#include "llvm/ADT/ScopeExit.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <type_traits>
Macros
#define DEBUG_TYPE "linalg-transforms"
#define DBGS() (llvm::dbgs() << "[" DEBUG_TYPE << "]: ")
Functions
static LogicalResult padOperandToSmallestStaticBoundingBox (PatternRewriter &rewriter, linalg::LinalgOp opToPad, OpOperand &operand, const LinalgTilingOptions &options, Value &result)
Try to compute a static bounding box for operand Return success if either:
static LogicalResult rewriteAsPaddedOp (PatternRewriter &rewriter, TiledLinalgOp &res, const LinalgTilingOptions &options)
static ValueRange getTiledOpResult (TiledLinalgOp tiledOp)
static ValueRange getTiledAndFusedOpResult (TiledAndFusedLinalgOps tiledAndFusedOp)
static AffineExpr substituteLoopInExpr (AffineExpr expr, AffineExpr dimExpr, Value lbVal, Value ubVal, Value stepVal, SmallVectorImpl< Value > &dims, SmallVectorImpl< Value > &symbols)
Given the lbVal, ubVal and stepVal of a loop, append lbVal and ubVal to dims and stepVal to symbols.
static AffineMap substitute (AffineMap map, SmallVectorImpl< Value > &dims, SmallVectorImpl< Value > &symbols, llvm::function_ref< bool(Operation *)> substituteOperation=nullptr)
Traverse the dims and substitute known min or max expressions in place of induction variables in exprs.
Macro Definition Documentation
DBGS
#define DBGS () (llvm::dbgs() << "[" DEBUG_TYPE << "]: ")
Definition at line 40 of file Transforms.cpp.
Referenced by mlir::linalg::applyStagedPatterns(), mlir::linalg::AffineMinSCFCanonicalizationPattern::matchAndRewrite(), substitute(), and substituteLoopInExpr().
DEBUG_TYPE
#define DEBUG_TYPE "linalg-transforms"
Definition at line 33 of file Transforms.cpp.
Function Documentation
getTiledAndFusedOpResult()
static ValueRange getTiledAndFusedOpResult (TiledAndFusedLinalgOps tiledAndFusedOp) static
Definition at line 297 of file Transforms.cpp.
References mlir::linalg::TiledAndFusedLinalgOps::fusedLoops, and mlir::linalg::TiledAndFusedLinalgOps::op.
Referenced by mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite().
getTiledOpResult()
static ValueRange getTiledOpResult (TiledLinalgOp tiledOp) static
Definition at line 290 of file Transforms.cpp.
References mlir::linalg::TiledLinalgOp::loops, and mlir::linalg::TiledLinalgOp::op.
Referenced by mlir::linalg::LinalgBaseTileAndFusePattern::matchAndRewrite().
padOperandToSmallestStaticBoundingBox()
static LogicalResult padOperandToSmallestStaticBoundingBox (PatternRewriter & rewriter, linalg::LinalgOp opToPad, OpOperand & operand, const LinalgTilingOptions & options, Value & result) static
Try to compute a static bounding box for operand Return success if either:
The operand is already statically shaped, result is left unchanged.
The operand is (partially) dynamic, result is the result of a freshly created PadTensorOp. Return failure if the operand cannot be padded to a static shape.
Definition at line 129 of file Transforms.cpp.
References mlir::Type::cast(), mlir::Attribute::dyn_cast(), mlir::failure(), mlir::OpOperand::get(), mlir::Value::getDefiningOp(), mlir::Value::getLoc(), mlir::linalg::getSmallestBoundingIndex(), mlir::Value::getType(), mlir::RewriterBase::notifyMatchFailure(), mlir::linalg::LinalgTilingOptions::paddingValueComputationFunction, and mlir::success().
Referenced by rewriteAsPaddedOp().
rewriteAsPaddedOp()
static LogicalResult rewriteAsPaddedOp (PatternRewriter & rewriter, TiledLinalgOp & res, const LinalgTilingOptions & options) static
Definition at line 166 of file Transforms.cpp.
References mlir::OpBuilder::create(), mlir::failed(), mlir::failure(), mlir::Builder::getIndexAttr(), mlir::IROperand< DerivedT, IRValueTy >::getOwner(), mlir::linalg::TiledLinalgOp::loops, mlir::linalg::TiledLinalgOp::op, padOperandToSmallestStaticBoundingBox(), mlir::RewriterBase::replaceOpWithIf(), mlir::OpBuilder::setInsertionPointAfter(), mlir::success(), and mlir::linalg::TiledLinalgOp::tensorResults.
Referenced by mlir::linalg::LinalgBaseTilingPattern::matchAndRewriteBase().
substitute()
static AffineMap substitute (AffineMap map, SmallVectorImpl< Value > & dims, SmallVectorImpl< Value > & symbols, llvm::function_ref< bool(Operation *)> substituteOperation = nullptr) static
Traverse the dims and substitute known min or max expressions in place of induction variables in exprs.
Definition at line 540 of file Transforms.cpp.
References mlir::canonicalizeMapAndOperands(), DBGS, mlir::fullyComposeAffineMapAndOperands(), mlir::AffineMap::get(), mlir::getAffineDimExpr(), mlir::AffineMap::getContext(), mlir::scf::getForInductionVarOwner(), mlir::AffineMap::getNumDims(), mlir::scf::getParallelForInductionVarOwner(), mlir::AffineMap::getResults(), mlir::simplifyAffineMap(), and substituteLoopInExpr().
Referenced by mlir::linalg::substituteMin().
substituteLoopInExpr()
static AffineExpr substituteLoopInExpr (AffineExpr expr, AffineExpr dimExpr, Value lbVal, Value ubVal, Value stepVal, SmallVectorImpl< Value > & dims, SmallVectorImpl< Value > & symbols) static
Given the lbVal, ubVal and stepVal of a loop, append lbVal and ubVal to dims and stepVal to symbols.
Create new AffineDimExpr (lb and ub) and AffineSymbolExpr (step) with positions matching the newly appended values. Substitute occurrences of dimExpr by either the min expression (i.e. lb) or the max expression (i.e. lb + step * floordiv(ub -1 - lb, step)), depending on whether the induction variable is used with a positive or negative coefficient.
Definition at line 520 of file Transforms.cpp.
References DBGS, mlir::floorDiv(), mlir::getAffineDimExpr(), mlir::getAffineSymbolExpr(), mlir::Value::getContext(), and mlir::substWithMin().
Referenced by substitute().