MLIR: lib/Conversion/StandardToSPIRV/LegalizeStandardForSPIRV.cpp File Reference
LegalizeStandardForSPIRV.cpp File Reference
#include "../PassDetail.h"
#include "mlir/Conversion/StandardToSPIRV/StandardToSPIRV.h"
#include "mlir/Conversion/StandardToSPIRV/StandardToSPIRVPass.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/SPIRV/IR/SPIRVDialect.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/Transforms/GreedyPatternRewriteDriver.h"
Functions
static Value getMemRefOperand (memref::LoadOp op)
Helpers to access the memref operand for each op.
static Value getMemRefOperand (vector::TransferReadOp op)
static Value getMemRefOperand (memref::StoreOp op)
static Value getMemRefOperand (vector::TransferWriteOp op)
static LogicalResult resolveSourceIndices (Location loc, PatternRewriter &rewriter, memref::SubViewOp subViewOp, ValueRange indices, SmallVectorImpl< Value > &sourceIndices)
Given the 'indices' of an load/store operation where the memref is a result of a subview op, returns the indices w.r.t to the source memref of the subview op.
Function Documentation
getMemRefOperand() [1/4]
static Value getMemRefOperand (memref::LoadOp op) static
Helpers to access the memref operand for each op.
Definition at line 27 of file LegalizeStandardForSPIRV.cpp.
Referenced by resolveSourceIndices().
getMemRefOperand() [2/4]
static Value getMemRefOperand (vector::TransferReadOp op) static
Definition at line 29 of file LegalizeStandardForSPIRV.cpp.
getMemRefOperand() [3/4]
static Value getMemRefOperand (memref::StoreOp op) static
Definition at line 31 of file LegalizeStandardForSPIRV.cpp.
getMemRefOperand() [4/4]
static Value getMemRefOperand (vector::TransferWriteOp op) static
Definition at line 33 of file LegalizeStandardForSPIRV.cpp.
References mlir::RewriterBase::replaceOpWithNewOp().
resolveSourceIndices()
static LogicalResult resolveSourceIndices (Location loc, PatternRewriter & rewriter, memref::SubViewOp subViewOp, ValueRange indices, SmallVectorImpl< Value > & sourceIndices) static
Given the 'indices' of an load/store operation where the memref is a result of a subview op, returns the indices w.r.t to the source memref of the subview op.
For example
%0 = ... : memref<12x42xf32> %1 = subview %0[arg0, arg1][][stride1, stride2] : memref<12x42xf32> to memref<4x4xf32, offset=?, strides=[?, ?]> %2 = load %1[i1, i2] : memref<4x4xf32, offset=?, strides=[?, ?]>
could be folded into
%2 = load %0[arg0 + i1 * stride1][arg1 + i2 * stride2] : memref<12x42xf32>
Definition at line 122 of file LegalizeStandardForSPIRV.cpp.
References mlir::OpBuilder::create(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), getMemRefOperand(), mlir::Range::offset, mlir::Range::stride, and mlir::success().