MLIR: include/mlir/Dialect/MemRef/EDSC/Intrinsics.h File Reference
Intrinsics.h File Reference
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/EDSC/Builders.h"
#include "mlir/Dialect/StandardOps/EDSC/Intrinsics.h"
#include "mlir/EDSC/Builders.h"
#include "llvm/ADT/SmallVector.h"
Classes
class mlir::edsc::MemRefBoundsCapture
A MemRefBoundsCapture represents the information required to step through a MemRef.
Namespaces
mlir
Include the generated interface declarations.
mlir::edsc
mlir::edsc::intrinsics
Typedefs
using mlir::edsc::intrinsics::memref_alloc = ValueBuilder< memref::AllocOp >
using mlir::edsc::intrinsics::memref_alloca = ValueBuilder< memref::AllocaOp >
using mlir::edsc::intrinsics::memref_cast = ValueBuilder< memref::CastOp >
using mlir::edsc::intrinsics::memref_dealloc = OperationBuilder< memref::DeallocOp >
using mlir::edsc::intrinsics::memref_dim = ValueBuilder< memref::DimOp >
using mlir::edsc::intrinsics::memref_load = ValueBuilder< memref::LoadOp >
using mlir::edsc::intrinsics::memref_store = OperationBuilder< memref::StoreOp >
using mlir::edsc::intrinsics::memref_sub_view = ValueBuilder< memref::SubViewOp >
using mlir::edsc::intrinsics::memref_tensor_load = ValueBuilder< memref::TensorLoadOp >
using mlir::edsc::intrinsics::memref_tensor_store = OperationBuilder< memref::TensorStoreOp >
using mlir::edsc::intrinsics::memref_view = ValueBuilder< memref::ViewOp >
using mlir::edsc::intrinsics::MemRefIndexedValue = TemplatedIndexedValue< intrinsics::memref_load, intrinsics::memref_store >
Provide an index notation around memref_load and memref_store.
Functions
static inline ::llvm::SmallVector< mlir::Value, 8 > getMemRefSizes (mlir::Value memRef)
Function Documentation
getMemRefSizes()
static inline ::llvm::SmallVector<mlir::Value, 8> getMemRefSizes (mlir::Value memRef) static
Definition at line 42 of file Intrinsics.h.
References mlir::Type::cast(), mlir::Value::getType(), and mlir::isStrided().
Referenced by mlir::edsc::MemRefBoundsCapture::MemRefBoundsCapture().