MLIR: lib/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.cpp File Reference
OpenMPToLLVMIRTranslation.cpp File Reference
#include "mlir/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.h"
#include "mlir/Dialect/OpenMP/OpenMPDialect.h"
#include "mlir/IR/Operation.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Target/LLVMIR/ModuleTranslation.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/TypeSwitch.h"
#include "llvm/Frontend/OpenMP/OMPIRBuilder.h"
#include "llvm/IR/IRBuilder.h"
Functions
static void convertOmpOpRegions (Region &region, StringRef blockName, llvm::BasicBlock &sourceBlock, llvm::BasicBlock &continuationBlock, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation, LogicalResult &bodyGenStatus)
Converts the given region that appears within an OpenMP dialect operation to LLVM IR, creating a branch from the sourceBlock to the entry block of the region, and a branch from any block with an successor-less OpenMP terminator to continuationBlock.
static LogicalResult convertOmpParallel (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts the OpenMP parallel operation to LLVM IR.
static LogicalResult convertOmpMaster (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP 'master' operation into LLVM IR using OpenMPIRBuilder.
static LogicalResult convertOmpWsLoop (Operation &opInst, llvm::IRBuilderBase &builder, LLVM::ModuleTranslation &moduleTranslation)
Converts an OpenMP workshare loop into LLVM IR using OpenMPIRBuilder.
Function Documentation
convertOmpMaster()
static LogicalResult convertOmpMaster (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP 'master' operation into LLVM IR using OpenMPIRBuilder.
Definition at line 143 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), and mlir::success().
Referenced by convertOmpWsLoop().
convertOmpOpRegions()
static void convertOmpOpRegions (Region & region, StringRef blockName, llvm::BasicBlock & sourceBlock, llvm::BasicBlock & continuationBlock, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation, LogicalResult & bodyGenStatus) static
Converts the given region that appears within an OpenMP dialect operation to LLVM IR, creating a branch from the sourceBlock to the entry block of the region, and a branch from any block with an successor-less OpenMP terminator to continuationBlock.
Definition at line 30 of file OpenMPToLLVMIRTranslation.cpp.
References mlir::LLVM::detail::connectPHINodes(), mlir::LLVM::ModuleTranslation::convertBlock(), mlir::failed(), mlir::failure(), mlir::LLVM::detail::getTopologicallySortedBlocks(), mlir::LLVM::ModuleTranslation::lookupBlock(), and mlir::LLVM::ModuleTranslation::mapBlock().
Referenced by convertOmpMaster(), convertOmpParallel(), and convertOmpWsLoop().
convertOmpParallel()
static LogicalResult convertOmpParallel (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts the OpenMP parallel operation to LLVM IR.
Definition at line 85 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpOpRegions(), mlir::failed(), mlir::failure(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVM::ModuleTranslation::lookupValue(), and mlir::success().
Referenced by convertOmpWsLoop().
convertOmpWsLoop()
static LogicalResult convertOmpWsLoop (Operation & opInst, llvm::IRBuilderBase & builder, LLVM::ModuleTranslation & moduleTranslation) static
Converts an OpenMP workshare loop into LLVM IR using OpenMPIRBuilder.
Definition at line 172 of file OpenMPToLLVMIRTranslation.cpp.
References convertOmpMaster(), convertOmpOpRegions(), convertOmpParallel(), mlir::Operation::emitError(), mlir::Operation::emitOpError(), mlir::failed(), mlir::failure(), mlir::Operation::getLoc(), mlir::Operation::getName(), mlir::Operation::getNumOperands(), mlir::LLVM::ModuleTranslation::getOpenMPBuilder(), mlir::LLVMTranslationDialectInterface::LLVMTranslationDialectInterface(), mlir::LLVM::ModuleTranslation::lookupValue(), mlir::LLVM::ModuleTranslation::mapValue(), mlir::success(), and mlir::LLVM::ModuleTranslation::translateLoc().