MLIR: lib/Dialect/Vector/VectorOps.cpp File Reference
VectorOps.cpp File Reference
#include "mlir/Dialect/Vector/VectorOps.h"
#include "mlir/Dialect/MemRef/IR/MemRef.h"
#include "mlir/Dialect/StandardOps/IR/Ops.h"
#include "mlir/Dialect/Tensor/IR/Tensor.h"
#include "mlir/Dialect/Utils/StructuredOpsUtils.h"
#include "mlir/Dialect/Vector/VectorUtils.h"
#include "mlir/IR/AffineExpr.h"
#include "mlir/IR/AffineMap.h"
#include "mlir/IR/BlockAndValueMapping.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/DialectImplementation.h"
#include "mlir/IR/OpImplementation.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/IR/TypeUtilities.h"
#include "mlir/Support/LLVM.h"
#include "mlir/Support/MathExtras.h"
#include "llvm/ADT/StringSet.h"
#include "llvm/ADT/bit.h"
#include <numeric>
#include "mlir/Dialect/Vector/VectorOpsEnums.cpp.inc"
#include "mlir/Dialect/Vector/VectorOps.cpp.inc"
Classes
struct mlir::vector::detail::BitmaskEnumStorage
struct CanonicalizeContractAdd< AddOpType >
Return a fused vector::ContractionOp which represents a patterns such as:
Namespaces
mlir
Include the generated interface declarations.
mlir::vector
mlir::vector::detail
Macros
#define GET_OP_LIST
#define GET_OP_CLASSES
Enumerations
enum MaskFormat { MaskFormat::AllTrue = 0, MaskFormat::AllFalse = 1, MaskFormat::Unknown = 2 }
Helper enum to classify mask value.
Functions
static MaskFormat get1DMaskFormat (Value mask)
Helper method to classify a 1-D mask value.
static bool isSupportedCombiningKind (CombiningKind combiningKind, Type elementType)
static LogicalResult verify (ReductionOp op)
static ParseResult parseReductionOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ReductionOp op)
static ParseResult parseContractionOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, ContractionOp op)
static bool verifyDimMap (VectorType lhsType, VectorType rhsType, const std::vector< std::pair< int64_t, int64_t >> &map)
static LogicalResult verifyOutputShape (ContractionOp op, VectorType lhsType, VectorType rhsType, Type accType, Type resType, const std::vector< std::pair< int64_t, int64_t >> &contractingDimMap, const std::vector< std::pair< int64_t, int64_t >> &batchDimMap)
static LogicalResult verify (ContractionOp op)
static int64_t getResultIndex (AffineMap map, AffineExpr targetExpr)
static std::vector< std::pair< int64_t, int64_t > > getDimMap (ArrayRef< AffineMap > indexingMaps, ArrayAttr iteratorTypes, StringRef targetIteratorTypeName, MLIRContext *context)
static LogicalResult verify (vector::ExtractElementOp op)
static Type inferExtractOpResultType (VectorType vectorType, ArrayAttr position)
static void print (OpAsmPrinter &p, vector::ExtractOp op)
static ParseResult parseExtractOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (vector::ExtractOp op)
template<typename IntType >
static SmallVector< IntType, 4 > extractVector (ArrayAttr arrayAttr)
static LogicalResult foldExtractOpFromExtractChain (ExtractOp extractOp)
Fold the result of chains of ExtractOp in place by simply concatenating the positions.
static LogicalResult foldExtractOpFromTranspose (ExtractOp extractOp)
Fold the result of an ExtractOp in place when it comes from a TransposeOp.
static Value foldExtractOpFromInsertChainAndTranspose (ExtractOp extractOp)
Fold an ExtractOp that is fed by a chain of InsertOps and TransposeOps.
static Value foldExtractFromBroadcast (ExtractOp extractOp)
Fold extractOp with scalar result coming from BroadcastOp.
static Value foldExtractFromShapeCast (ExtractOp extractOp)
static LogicalResult isValidExtractOrInsertSlicesType (Operation *op, VectorType vectorType, TupleType tupleType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides)
static LogicalResult verify (ExtractSlicesOp op)
static void populateFromInt64AttrArray (ArrayAttr arrayAttr, SmallVectorImpl< int64_t > &results)
static LogicalResult verify (ExtractMapOp op)
template<typename MapOp >
AffineMap calculateImplicitMap (MapOp op)
static LogicalResult verify (BroadcastOp op)
static void print (OpAsmPrinter &p, ShuffleOp op)
static LogicalResult verify (ShuffleOp op)
static ParseResult parseShuffleOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (InsertElementOp op)
static LogicalResult verify (InsertOp op)
static LogicalResult verify (InsertSlicesOp op)
static LogicalResult verify (InsertMapOp op)
template<typename OpType >
static LogicalResult isIntegerArrayAttrSmallerThanShape (OpType op, ArrayAttr arrayAttr, ArrayRef< int64_t > shape, StringRef attrName)
template<typename OpType >
static LogicalResult isIntegerArrayAttrConfinedToRange (OpType op, ArrayAttr arrayAttr, int64_t min, int64_t max, StringRef attrName, bool halfOpen=true)
template<typename OpType >
static LogicalResult isIntegerArrayAttrConfinedToShape (OpType op, ArrayAttr arrayAttr, ArrayRef< int64_t > shape, StringRef attrName, bool halfOpen=true, int64_t min=0)
template<typename OpType >
static LogicalResult isSumOfIntegerArrayAttrConfinedToShape (OpType op, ArrayAttr arrayAttr1, ArrayAttr arrayAttr2, ArrayRef< int64_t > shape, StringRef attrName1, StringRef attrName2, bool halfOpen=true, int64_t min=1)
static ArrayAttr makeI64ArrayAttr (ArrayRef< int64_t > values, MLIRContext *context)
static LogicalResult verify (InsertStridedSliceOp op)
static void print (OpAsmPrinter &p, OuterProductOp op)
static ParseResult parseOuterProductOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (OuterProductOp op)
static LogicalResult verify (ReshapeOp op)
static Type inferStridedSliceOpResultType (VectorType vectorType, ArrayAttr offsets, ArrayAttr sizes, ArrayAttr strides)
static LogicalResult verify (ExtractStridedSliceOp op)
static LogicalResult foldExtractStridedOpFromInsertChain (ExtractStridedSliceOp op)
template<typename EmitFun >
static LogicalResult verifyPermutationMap (AffineMap permutationMap, EmitFun emitOpError)
static LogicalResult verifyTransferOp (Operation *op, ShapedType shapedType, VectorType vectorType, AffineMap permutationMap, ArrayAttr inBounds)
static void printTransferAttrs (OpAsmPrinter &p, VectorTransferOpInterface op)
static void print (OpAsmPrinter &p, TransferReadOp op)
static ParseResult parseTransferReadOp (OpAsmParser &parser, OperationState &result)
static LogicalResult verify (TransferReadOp op)
static LogicalResult foldMemRefCast (Operation *op)
This is a common class used for patterns of the form
someop(memrefcast) -> someop
It folds the source of the memref.cast into the root operation directly.
static LogicalResult foldTensorCast (Operation *op)
template<typename TransferOp >
static bool isInBounds (TransferOp op, int64_t resultIdx, int64_t indicesIdx)
template<typename TransferOp >
static LogicalResult foldTransferInBoundsAttribute (TransferOp op)
static ParseResult parseTransferWriteOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, TransferWriteOp op)
static LogicalResult verify (TransferWriteOp op)
static LogicalResult foldReadInitWrite (TransferWriteOp write, ArrayRef< Attribute >, SmallVectorImpl< OpFoldResult > &results)
Fold: ``` t1 = ...
static LogicalResult verifyLoadStoreMemRefLayout (Operation *op, MemRefType memRefTy)
static LogicalResult verify (vector::LoadOp op)
static LogicalResult verify (vector::StoreOp op)
static LogicalResult verify (MaskedLoadOp op)
static LogicalResult verify (MaskedStoreOp op)
static LogicalResult verify (GatherOp op)
static LogicalResult verify (ScatterOp op)
static LogicalResult verify (ExpandLoadOp op)
static LogicalResult verify (CompressStoreOp op)
static bool isValidShapeCast (ArrayRef< int64_t > a, ArrayRef< int64_t > b)
Returns true if each element of 'a' is equal to the product of a contiguous sequence of the elements of 'b'.
static LogicalResult verifyVectorShapeCast (Operation *op, VectorType sourceVectorType, VectorType resultVectorType)
static LogicalResult verify (ShapeCastOp op)
static LogicalResult verify (BitCastOp op)
static SmallVector< int64_t, 8 > extractShape (MemRefType memRefType)
static LogicalResult verify (TypeCastOp op)
static ParseResult parseTupleOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, TupleOp op)
static LogicalResult verify (TupleOp op)
static LogicalResult verify (vector::TransposeOp op)
static ParseResult parseTupleGetOp (OpAsmParser &parser, OperationState &result)
static void print (OpAsmPrinter &p, TupleGetOp op)
static LogicalResult verify (TupleGetOp op)
static LogicalResult verify (ConstantMaskOp &op)
static LogicalResult verify (CreateMaskOp op)
Variables
static constexpr const CombiningKind combiningKindsList []
Macro Definition Documentation
GET_OP_CLASSES
#define GET_OP_CLASSES
Definition at line 3617 of file VectorOps.cpp.
GET_OP_LIST
#define GET_OP_LIST
Enumeration Type Documentation
MaskFormat
enum MaskFormat strong
Helper enum to classify mask value.
Enumerator
AllTrue
AllFalse
Unknown
Definition at line 42 of file VectorOps.cpp.
Function Documentation
calculateImplicitMap()
template<typename MapOp > AffineMap calculateImplicitMap (MapOp op)
Definition at line 1246 of file VectorOps.cpp.
References mlir::AffineMap::get(), mlir::getAffineDimExpr(), and getVectorType().
Referenced by verify().
extractShape()
static SmallVector<int64_t, 8> extractShape (MemRefType memRefType) static
Definition at line 3292 of file VectorOps.cpp.
References mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::getElementTypeOrSelf(), mlir::Value::getType(), and vectorType().
Referenced by verify().
extractVector()
template<typename IntType > static SmallVector<IntType, 4> extractVector (ArrayAttr arrayAttr) static
Definition at line 832 of file VectorOps.cpp.
foldExtractFromBroadcast()
static Value foldExtractFromBroadcast (ExtractOp extractOp) static
Fold extractOp with scalar result coming from BroadcastOp.
Definition at line 1003 of file VectorOps.cpp.
References mlir::Type::cast(), mlir::Value::getDefiningOp(), and mlir::Type::isa().
Referenced by foldExtractFromShapeCast().
foldExtractFromShapeCast()
static Value foldExtractFromShapeCast (ExtractOp extractOp) static
Definition at line 1034 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Type::cast(), mlir::delinearize(), foldExtractFromBroadcast(), foldExtractOpFromExtractChain(), foldExtractOpFromInsertChainAndTranspose(), foldExtractOpFromTranspose(), mlir::Value::getDefiningOp(), mlir::getStridesAttrName(), mlir::Value::getType(), mlir::vector::getVectorSubscriptAttr(), mlir::linearize(), and mlir::succeeded().
foldExtractOpFromExtractChain()
static LogicalResult foldExtractOpFromExtractChain (ExtractOp extractOp) static
Fold the result of chains of ExtractOp in place by simply concatenating the positions.
Definition at line 840 of file VectorOps.cpp.
References mlir::failure(), and mlir::success().
Referenced by foldExtractFromShapeCast().
foldExtractOpFromInsertChainAndTranspose()
static Value foldExtractOpFromInsertChainAndTranspose (ExtractOp extractOp) static
Fold an ExtractOp that is fed by a chain of InsertOps and TransposeOps.
The result is always the input to some InsertOp.
Definition at line 921 of file VectorOps.cpp.
References mlir::AffineMap::compose(), mlir::Value::getDefiningOp(), mlir::AffineMap::getDimPosition(), mlir::AffineMap::getMinorSubMap(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getPermutationMap(), mlir::AffineMap::isIdentity(), mlir::AffineMap::isMinorIdentity(), and mlir::AffineMap::isPermutation().
Referenced by foldExtractFromShapeCast().
foldExtractOpFromTranspose()
static LogicalResult foldExtractOpFromTranspose (ExtractOp extractOp) static
Fold the result of an ExtractOp in place when it comes from a TransposeOp.
Definition at line 863 of file VectorOps.cpp.
References mlir::AffineMap::compose(), mlir::failure(), mlir::AffineMap::get(), mlir::AffineMap::getMajorSubMap(), mlir::AffineMap::getMinorSubMap(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getPermutationMap(), mlir::AffineDimExpr::getPosition(), mlir::AffineMap::getResults(), mlir::inversePermutation(), mlir::AffineMap::isMinorIdentity(), and mlir::success().
Referenced by foldExtractFromShapeCast().
foldExtractStridedOpFromInsertChain()
static LogicalResult foldExtractStridedOpFromInsertChain (ExtractStridedSliceOp op) static
Definition at line 1937 of file VectorOps.cpp.
References mlir::RewritePatternSet::add(), broadcast(), mlir::Attribute::cast(), mlir::OpBuilder::create(), dropFront(), mlir::Type::dyn_cast(), extractStrides(), mlir::failure(), mlir::DenseElementsAttr::get(), mlir::Value::getDefiningOp(), getI64SubArray(), mlir::Value::getType(), mlir::vector::getVectorSubscriptAttr(), getVectorType(), max(), min(), populateFromInt64AttrArray(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::succeeded(), and mlir::success().
foldMemRefCast()
static LogicalResult foldMemRefCast (Operation * op) static
This is a common class used for patterns of the form
someop(memrefcast) -> someop
It folds the source of the memref.cast into the root operation directly.
Definition at line 2444 of file VectorOps.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::Operation::getOpOperands(), and mlir::success().
Referenced by foldReadInitWrite(), and foldTransferInBoundsAttribute().
foldReadInitWrite()
static LogicalResult foldReadInitWrite (TransferWriteOp write, ArrayRef< Attribute > , SmallVectorImpl< OpFoldResult > & results) static
Fold: ``` t1 = ...
v = vector.transfer_read t0[c0...], {in_bounds = [true...]} : tensor<static_sizesxf32>, vector<static_sizesxf32> t2 = vector.transfer_write v, t1[c0...] {in_bounds = [true...]} : vector<static_sizesxf32>, tensor<static_sizesxf32>
into:
t0 ```
The producer of t1 may or may not be DCE'd depending on whether it is a block argument or has side effects.
Definition at line 2684 of file VectorOps.cpp.
References mlir::failure(), foldMemRefCast(), foldTransferInBoundsAttribute(), mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), mlir::ConstantIndexOp::getValue(), getVectorType(), mlir::succeeded(), and mlir::success().
foldTensorCast()
static LogicalResult foldTensorCast (Operation * op) static
Definition at line 2456 of file VectorOps.cpp.
References mlir::tensor::canFoldIntoConsumerOp(), mlir::Operation::getOpOperands(), and mlir::success().
Referenced by foldTransferInBoundsAttribute().
foldTransferInBoundsAttribute()
template<typename TransferOp > static LogicalResult foldTransferInBoundsAttribute (TransferOp op) static
Definition at line 2486 of file VectorOps.cpp.
References mlir::Type::cast(), mlir::Type::dyn_cast(), mlir::failure(), foldMemRefCast(), foldTensorCast(), mlir::SideEffects::Effect::Base< DerivedEffect, BaseEffect >::get(), mlir::SideEffects::Resource::Base< DefaultResource >::get(), mlir::Builder::getBoolArrayAttr(), mlir::vector::impl::getTransferMinorIdentityMap(), mlir::Value::getType(), getVectorType(), isInBounds(), mlir::AffineMap::isMinorIdentity(), mlir::succeeded(), and mlir::success().
Referenced by foldReadInitWrite().
get1DMaskFormat()
static MaskFormat get1DMaskFormat (Value mask) static
Helper method to classify a 1-D mask value.
Currently, the method looks "under the hood" of a constant value with dense attributes and a constant mask operation (since the client may be called at various stages during progressive lowering).
Definition at line 52 of file VectorOps.cpp.
References AllFalse, AllTrue, mlir::Value::getDefiningOp(), and Unknown.
Referenced by verify().
getDimMap()
static std::vector<std::pair<int64_t, int64_t> > getDimMap (ArrayRef< AffineMap > indexingMaps, ArrayAttr iteratorTypes, StringRef targetIteratorTypeName, MLIRContext * context) static
Definition at line 583 of file VectorOps.cpp.
References mlir::Attribute::cast(), mlir::AffineExpr::cast(), mlir::detail::enumerate(), mlir::getAffineDimExpr(), mlir::getParallelIteratorTypeName(), mlir::getReductionIteratorTypeName(), and getResultIndex().
getResultIndex()
static int64_t getResultIndex (AffineMap map, AffineExpr targetExpr) static
Definition at line 575 of file VectorOps.cpp.
References mlir::AffineMap::getNumResults(), and mlir::AffineMap::getResult().
Referenced by getDimMap().
inferExtractOpResultType()
static Type inferExtractOpResultType (VectorType vectorType, ArrayAttr position) static
Definition at line 750 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Type::cast(), mlir::Value::getDefiningOp(), mlir::Value::getType(), and mlir::vector::getVectorSubscriptAttr().
Referenced by parseExtractOp().
inferStridedSliceOpResultType()
static Type inferStridedSliceOpResultType (VectorType vectorType, ArrayAttr offsets, ArrayAttr sizes, ArrayAttr strides) static
Definition at line 1862 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Type::cast(), mlir::getStridesAttrName(), mlir::Value::getType(), and mlir::vector::getVectorSubscriptAttr().
Referenced by verify().
isInBounds()
template<typename TransferOp > static bool isInBounds (TransferOp op, int64_t resultIdx, int64_t indicesIdx) static
Definition at line 2469 of file VectorOps.cpp.
References mlir::Value::getDefiningOp(), and mlir::ConstantIndexOp::getValue().
Referenced by foldTransferInBoundsAttribute().
isIntegerArrayAttrConfinedToRange()
template<typename OpType > static LogicalResult isIntegerArrayAttrConfinedToRange (OpType op, ArrayAttr arrayAttr, int64_t min, int64_t max, StringRef attrName, bool halfOpen = true) static
Definition at line 1587 of file VectorOps.cpp.
References mlir::Attribute::cast(), max(), and mlir::success().
Referenced by verify().
isIntegerArrayAttrConfinedToShape()
template<typename OpType > static LogicalResult isIntegerArrayAttrConfinedToShape (OpType op, ArrayAttr arrayAttr, ArrayRef< int64_t > shape, StringRef attrName, bool halfOpen = true, int64_t min = 0) static
Definition at line 1607 of file VectorOps.cpp.
References max(), min(), and mlir::success().
Referenced by verify().
isIntegerArrayAttrSmallerThanShape()
template<typename OpType > static LogicalResult isIntegerArrayAttrSmallerThanShape (OpType op, ArrayAttr arrayAttr, ArrayRef< int64_t > shape, StringRef attrName) static
Definition at line 1572 of file VectorOps.cpp.
References mlir::success().
Referenced by verify().
isSumOfIntegerArrayAttrConfinedToShape()
template<typename OpType > static LogicalResult isSumOfIntegerArrayAttrConfinedToShape (OpType op, ArrayAttr arrayAttr1, ArrayAttr arrayAttr2, ArrayRef< int64_t > shape, StringRef attrName1, StringRef attrName2, bool halfOpen = true, int64_t min = 1) static
Definition at line 1630 of file VectorOps.cpp.
References max(), min(), and mlir::success().
Referenced by verify().
isSupportedCombiningKind()
static bool isSupportedCombiningKind (CombiningKind combiningKind, Type elementType) static
Definition at line 88 of file VectorOps.cpp.
References mlir::Type::isIntOrIndex(), and mlir::Type::isIntOrIndexOrFloat().
Referenced by verify().
isValidExtractOrInsertSlicesType()
static LogicalResult isValidExtractOrInsertSlicesType (Operation * op, VectorType vectorType, TupleType tupleType, ArrayRef< int64_t > sizes, ArrayRef< int64_t > strides) static
Definition at line 1123 of file VectorOps.cpp.
References mlir::computeElementOffsetsFromVectorSliceOffsets(), mlir::computeSliceSizes(), mlir::computeStrides(), mlir::delinearize(), mlir::Operation::emitError(), and mlir::success().
Referenced by verify().
isValidShapeCast()
static bool isValidShapeCast (ArrayRef< int64_t > a, ArrayRef< int64_t > b) static
Returns true if each element of 'a' is equal to the product of a contiguous sequence of the elements of 'b'.
Returns false otherwise.
Definition at line 3096 of file VectorOps.cpp.
Referenced by verifyVectorShapeCast().
makeI64ArrayAttr()
static ArrayAttr makeI64ArrayAttr (ArrayRef< int64_t > values, MLIRContext * context) static
Definition at line 1652 of file VectorOps.cpp.
Referenced by verify().
parseContractionOp()
static ParseResult parseContractionOp (OpAsmParser & parser, OperationState & result) static
Definition at line 327 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OpAsmParser::addTypeToList(), mlir::NamedAttrList::assign(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::vector::CombiningKindAttr::get(), mlir::NamedAttrList::get(), mlir::OpAsmParser::getBuilder(), mlir::OperationState::getContext(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI1Type(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseTrailingOperandList(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::success(), and mlir::OperationState::types.
parseExtractOp()
static ParseResult parseExtractOp (OpAsmParser & parser, OperationState & result) static
Definition at line 783 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::Attribute::dyn_cast(), mlir::Type::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getCurrentLocation(), inferExtractOpResultType(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::OperationState::types, and vectorType().
parseOuterProductOp()
static ParseResult parseOuterProductOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1716 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::NamedAttrList::append(), mlir::OperationState::attributes, mlir::Type::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::vector::CombiningKindAttr::get(), mlir::NamedAttrList::get(), mlir::OperationState::getContext(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), and mlir::OperationState::types.
parseReductionOp()
static ParseResult parseReductionOp (OpAsmParser & parser, OperationState & result) static
Definition at line 268 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getNameLoc(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseKeywordType(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::resolveOperand(), mlir::success(), and mlir::OperationState::types.
parseShuffleOp()
static ParseResult parseShuffleOp (OpAsmParser & parser, OperationState & result) static
Definition at line 1392 of file VectorOps.cpp.
References mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::OpBuilder::create(), mlir::Attribute::dyn_cast(), mlir::OpAsmParser::emitError(), mlir::failure(), mlir::OpAsmParser::getNameLoc(), mlir::Value::getType(), mlir::OperationState::location, mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseType(), mlir::OpAsmParser::resolveOperand(), mlir::success(), and mlir::OperationState::types.
parseTransferReadOp()
static ParseResult parseTransferReadOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2348 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::NamedAttrList::get(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI1Type(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::vector::impl::getTransferMinorIdentityMap(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::NamedAttrList::set(), mlir::OpAsmParser::Square, mlir::LogicalResult::succeeded(), and mlir::OperationState::types.
parseTransferWriteOp()
static ParseResult parseTransferWriteOp (OpAsmParser & parser, OperationState & result) static
Definition at line 2590 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::OpAsmParser::emitError(), mlir::failure(), mlir::NamedAttrList::get(), mlir::OpAsmParser::getBuilder(), mlir::OpAsmParser::getCurrentLocation(), mlir::Builder::getI1Type(), mlir::Builder::getI32VectorAttr(), mlir::Builder::getIndexType(), mlir::vector::impl::getTransferMinorIdentityMap(), mlir::Type::isa(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::parseOptionalComma(), mlir::OpAsmParser::resolveOperand(), mlir::OpAsmParser::resolveOperands(), mlir::NamedAttrList::set(), mlir::OpAsmParser::Square, mlir::LogicalResult::succeeded(), and mlir::OperationState::types.
parseTupleGetOp()
static ParseResult parseTupleGetOp (OpAsmParser & parser, OperationState & result) static
Definition at line 3480 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getIndexType(), mlir::OperationState::operands, mlir::OpAsmParser::parseAttribute(), mlir::OpAsmParser::parseColonType(), mlir::OpAsmParser::parseComma(), mlir::OpAsmParser::parseOperand(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperand(), mlir::success(), and mlir::OperationState::types.
parseTupleOp()
static ParseResult parseTupleOp (OpAsmParser & parser, OperationState & result) static
Definition at line 3342 of file VectorOps.cpp.
References mlir::OpAsmParser::addTypeToList(), mlir::OperationState::attributes, mlir::failure(), mlir::OpAsmParser::getBuilder(), mlir::Builder::getContext(), mlir::OpAsmParser::getCurrentLocation(), mlir::OperationState::operands, mlir::OpAsmParser::parseColonTypeList(), mlir::OpAsmParser::parseOperandList(), mlir::OpAsmParser::parseOptionalAttrDict(), mlir::OpAsmParser::resolveOperands(), and mlir::OperationState::types.
populateFromInt64AttrArray()
static void populateFromInt64AttrArray (ArrayAttr arrayAttr, SmallVectorImpl< int64_t > & results) static
Definition at line 1170 of file VectorOps.cpp.
References mlir::Attribute::cast(), mlir::AffineExpr::cast(), mlir::Type::cast(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getResult(), mlir::Value::getType(), and mlir::AffineMap::isProjectedPermutation().
Referenced by foldExtractStridedOpFromInsertChain(), and verify().
print() [1/9]
static void print (OpAsmPrinter & p, ReductionOp op) static
Definition at line 290 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::vector::CombiningKindAttr::get(), mlir::Builder::getAffineMapArrayAttr(), mlir::Builder::getContext(), mlir::getIndexingMapsAttrName(), mlir::getIteratorTypesAttrName(), mlir::Builder::getStrArrayAttr(), mlir::Value::getType(), and mlir::AffineMap::inferFromExprList().
print() [2/9]
static void print (OpAsmPrinter & p, ContractionOp op) static
Definition at line 374 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [3/9]
static void print (OpAsmPrinter & p, vector::ExtractOp op) static
Definition at line 777 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [4/9]
static void print (OpAsmPrinter & p, ShuffleOp op) static
Definition at line 1351 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [5/9]
static void print (OpAsmPrinter & p, OuterProductOp op) static
Definition at line 1707 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
print() [6/9]
static void print (OpAsmPrinter & p, TransferReadOp op) static
Definition at line 2339 of file VectorOps.cpp.
References printTransferAttrs().
print() [7/9]
static void print (OpAsmPrinter & p, TransferWriteOp op) static
Definition at line 2640 of file VectorOps.cpp.
References printTransferAttrs().
print() [8/9]
static void print (OpAsmPrinter & p, TupleOp op) static
Definition at line 3355 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOperands(), and mlir::OpAsmPrinter::printOptionalAttrDict().
print() [9/9]
static void print (OpAsmPrinter & p, TupleGetOp op) static
Definition at line 3501 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
printTransferAttrs()
static void printTransferAttrs (OpAsmPrinter & p, VectorTransferOpInterface op) static
Definition at line 2320 of file VectorOps.cpp.
References mlir::OpAsmPrinter::printOptionalAttrDict().
Referenced by print().
verify() [1/34]
static LogicalResult verify (ReductionOp op) static
Definition at line 238 of file VectorOps.cpp.
References mlir::Type::isa(), mlir::Type::isIntOrIndex(), mlir::Type::isIntOrIndexOrFloat(), and mlir::success().
verify() [2/34]
static LogicalResult verify (ContractionOp op) static
Definition at line 492 of file VectorOps.cpp.
References elementType(), mlir::detail::enumerate(), mlir::failed(), mlir::failure(), mlir::getIndexingMapsAttrName(), mlir::getIteratorTypesAttrName(), isSupportedCombiningKind(), mlir::success(), vectorType(), verifyDimMap(), and verifyOutputShape().
verify() [3/34]
static LogicalResult verify (vector::ExtractElementOp op) static
Definition at line 739 of file VectorOps.cpp.
References mlir::success(), and vectorType().
verify() [4/34]
static LogicalResult verify (vector::ExtractOp op) static
Definition at line 812 of file VectorOps.cpp.
References mlir::Attribute::dyn_cast(), mlir::detail::enumerate(), and mlir::success().
verify() [5/34]
static LogicalResult verify (ExtractSlicesOp op) static
Definition at line 1160 of file VectorOps.cpp.
References isValidExtractOrInsertSlicesType().
verify() [6/34]
static LogicalResult verify (ExtractMapOp op) static
Definition at line 1207 of file VectorOps.cpp.
References mlir::Value::getDefiningOp(), and mlir::success().
verify() [7/34]
static LogicalResult verify (BroadcastOp op) static
Definition at line 1274 of file VectorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::failure(), mlir::DenseElementsAttr::get(), mlir::Value::getType(), mlir::vector::getVectorSubscriptAttr(), getVectorType(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and vectorType().
verify() [8/34]
static LogicalResult verify (ShuffleOp op) static
Definition at line 1358 of file VectorOps.cpp.
References mlir::Attribute::dyn_cast(), mlir::detail::enumerate(), and mlir::success().
verify() [9/34]
static LogicalResult verify (InsertElementOp op) static
Definition at line 1441 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Value::getDefiningOp(), mlir::Value::getType(), mlir::vector::getVectorSubscriptAttr(), and mlir::success().
verify() [10/34]
static LogicalResult verify (InsertOp op) static
Definition at line 1470 of file VectorOps.cpp.
References mlir::Attribute::dyn_cast(), mlir::detail::enumerate(), and mlir::success().
verify() [11/34]
static LogicalResult verify (InsertSlicesOp op) static
Definition at line 1504 of file VectorOps.cpp.
References mlir::Value::getType(), isValidExtractOrInsertSlicesType(), and populateFromInt64AttrArray().
verify() [12/34]
static LogicalResult verify (InsertMapOp op) static
Definition at line 1531 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), calculateImplicitMap(), mlir::getStridesAttrName(), mlir::Value::getType(), mlir::vector::getVectorSubscriptAttr(), and mlir::success().
verify() [13/34]
static LogicalResult verify (InsertStridedSliceOp op) static
Definition at line 1660 of file VectorOps.cpp.
References mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::failed(), mlir::failure(), mlir::getStridesAttrName(), mlir::Value::getType(), isIntegerArrayAttrConfinedToRange(), isIntegerArrayAttrConfinedToShape(), isSumOfIntegerArrayAttrConfinedToShape(), makeI64ArrayAttr(), and mlir::success().
verify() [14/34]
static LogicalResult verify (OuterProductOp op) static
Definition at line 1753 of file VectorOps.cpp.
References mlir::Type::dyn_cast(), isSupportedCombiningKind(), and mlir::success().
verify() [15/34]
static LogicalResult verify (ReshapeOp op) static
Definition at line 1794 of file VectorOps.cpp.
References populateFromInt64AttrArray(), and mlir::success().
verify() [16/34]
static LogicalResult verify (ExtractStridedSliceOp op) static
Definition at line 1893 of file VectorOps.cpp.
References mlir::failed(), mlir::failure(), mlir::getStridesAttrName(), inferStridedSliceOpResultType(), isIntegerArrayAttrConfinedToRange(), isIntegerArrayAttrConfinedToShape(), isIntegerArrayAttrSmallerThanShape(), isSumOfIntegerArrayAttrConfinedToShape(), and mlir::success().
verify() [17/34]
static LogicalResult verify (TransferReadOp op) static
Definition at line 2401 of file VectorOps.cpp.
References mlir::failed(), mlir::failure(), mlir::ShapedType::getElementType(), mlir::ShapedType::getRank(), vectorType(), verifyPermutationMap(), and verifyTransferOp().
verify() [18/34]
static LogicalResult verify (TransferWriteOp op) static
Definition at line 2649 of file VectorOps.cpp.
References mlir::failed(), mlir::failure(), mlir::ShapedType::getRank(), vectorType(), verifyPermutationMap(), and verifyTransferOp().
verify() [19/34]
static LogicalResult verify (vector::LoadOp op) static
Definition at line 2760 of file VectorOps.cpp.
References mlir::Type::dyn_cast(), mlir::failed(), mlir::failure(), mlir::success(), and verifyLoadStoreMemRefLayout().
verify() [20/34]
static LogicalResult verify (vector::StoreOp op) static
Definition at line 2786 of file VectorOps.cpp.
References mlir::Type::dyn_cast(), mlir::failed(), mlir::failure(), mlir::success(), and verifyLoadStoreMemRefLayout().
verify() [21/34]
static LogicalResult verify (MaskedLoadOp op) static
Definition at line 2813 of file VectorOps.cpp.
References mlir::RewritePatternSet::add(), AllFalse, AllTrue, mlir::failure(), get1DMaskFormat(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and Unknown.
verify() [22/34]
static LogicalResult verify (MaskedStoreOp op) static
Definition at line 2861 of file VectorOps.cpp.
References mlir::RewritePatternSet::add(), AllFalse, AllTrue, mlir::RewriterBase::eraseOp(), mlir::failure(), get1DMaskFormat(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and Unknown.
verify() [23/34]
static LogicalResult verify (GatherOp op) static
Definition at line 2906 of file VectorOps.cpp.
References mlir::RewritePatternSet::add(), AllFalse, AllTrue, mlir::failure(), get1DMaskFormat(), mlir::RewriterBase::replaceOp(), mlir::success(), and Unknown.
verify() [24/34]
static LogicalResult verify (ScatterOp op) static
Definition at line 2954 of file VectorOps.cpp.
References mlir::RewritePatternSet::add(), AllFalse, AllTrue, mlir::RewriterBase::eraseOp(), mlir::failure(), get1DMaskFormat(), mlir::success(), and Unknown.
verify() [25/34]
static LogicalResult verify (ExpandLoadOp op) static
Definition at line 3000 of file VectorOps.cpp.
References mlir::RewritePatternSet::add(), AllFalse, AllTrue, mlir::failure(), get1DMaskFormat(), mlir::RewriterBase::replaceOp(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and Unknown.
verify() [26/34]
static LogicalResult verify (CompressStoreOp op) static
Definition at line 3048 of file VectorOps.cpp.
References mlir::RewritePatternSet::add(), AllFalse, AllTrue, mlir::RewriterBase::eraseOp(), mlir::failure(), get1DMaskFormat(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and Unknown.
verify() [27/34]
static LogicalResult verify (ShapeCastOp op) static
Definition at line 3154 of file VectorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::failed(), mlir::failure(), mlir::DenseElementsAttr::get(), mlir::RewriterBase::replaceOpWithNewOp(), mlir::success(), and verifyVectorShapeCast().
verify() [28/34]
static LogicalResult verify (BitCastOp op) static
Definition at line 3231 of file VectorOps.cpp.
References mlir::DataLayout::closest(), mlir::Attribute::dyn_cast(), mlir::DenseElementsAttr::get(), mlir::DataLayout::getTypeSizeInBits(), mlir::Type::isF16(), mlir::Type::isF32(), and mlir::success().
verify() [29/34]
static LogicalResult verify (TypeCastOp op) static
Definition at line 3314 of file VectorOps.cpp.
References mlir::canonicalizeStridedLayout(), extractShape(), mlir::getElementTypeOrSelf(), and mlir::success().
verify() [30/34]
static LogicalResult verify (TupleOp op) static
Definition at line 3363 of file VectorOps.cpp.
References mlir::OperationState::addAttribute(), mlir::OperationState::addOperands(), mlir::OperationState::addTypes(), mlir::Type::cast(), mlir::Builder::getI64ArrayAttr(), mlir::Value::getType(), and mlir::success().
verify() [31/34]
static LogicalResult verify (vector::TransposeOp op) static
Definition at line 3398 of file VectorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::detail::enumerate(), mlir::failure(), mlir::vector::getVectorSubscriptAttr(), populateFromInt64AttrArray(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
verify() [32/34]
static LogicalResult verify (TupleGetOp op) static
Definition at line 3508 of file VectorOps.cpp.
References mlir::success().
verify() [33/34]
static LogicalResult verify (ConstantMaskOp & op) static
Definition at line 3532 of file VectorOps.cpp.
References mlir::detail::enumerate(), and mlir::success().
verify() [34/34]
static LogicalResult verify (CreateMaskOp op) static
Definition at line 3563 of file VectorOps.cpp.
References mlir::RewritePatternSet::add(), mlir::failure(), mlir::vector::getVectorSubscriptAttr(), mlir::RewriterBase::replaceOpWithNewOp(), and mlir::success().
verifyDimMap()
static bool verifyDimMap (VectorType lhsType, VectorType rhsType, const std::vector< std::pair< int64_t, int64_t >> & map) static
Definition at line 395 of file VectorOps.cpp.
Referenced by verify().
verifyLoadStoreMemRefLayout()
static LogicalResult verifyLoadStoreMemRefLayout (Operation * op, MemRefType memRefTy) static
Definition at line 2752 of file VectorOps.cpp.
References mlir::Operation::emitOpError(), and mlir::success().
Referenced by verify().
verifyOutputShape()
static LogicalResult verifyOutputShape (ContractionOp op, VectorType lhsType, VectorType rhsType, Type accType, Type resType, const std::vector< std::pair< int64_t, int64_t >> & contractingDimMap, const std::vector< std::pair< int64_t, int64_t >> & batchDimMap) static
Definition at line 406 of file VectorOps.cpp.
References mlir::AffineExpr::cast(), mlir::AffineMap::compose(), mlir::Type::dyn_cast(), mlir::AffineMap::get(), mlir::getAffineConstantExpr(), mlir::AffineMap::getNumInputs(), mlir::AffineExpr::isa(), mlir::Type::isa(), mlir::simplifyAffineMap(), and mlir::success().
Referenced by verify().
verifyPermutationMap()
template<typename EmitFun > static LogicalResult verifyPermutationMap (AffineMap permutationMap, EmitFun emitOpError) static
Definition at line 2164 of file VectorOps.cpp.
References mlir::AffineExpr::dyn_cast(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getResults(), and mlir::success().
Referenced by verify().
verifyTransferOp()
static LogicalResult verifyTransferOp (Operation * op, ShapedType shapedType, VectorType vectorType, AffineMap permutationMap, ArrayAttr inBounds) static
Definition at line 2192 of file VectorOps.cpp.
References mlir::Type::cast(), mlir::DataLayout::closest(), mlir::OpBuilder::create(), mlir::Type::dyn_cast(), elementType(), mlir::Operation::emitOpError(), mlir::Builder::getBoolArrayAttr(), mlir::ShapedType::getElementType(), getElementType(), mlir::AffineMap::getNumInputs(), mlir::AffineMap::getNumResults(), mlir::AffineMap::getNumSymbols(), mlir::ShapedType::getRank(), mlir::vector::impl::getTransferMinorIdentityMap(), mlir::Value::getType(), mlir::DataLayout::getTypeSizeInBits(), mlir::Builder::getZeroAttr(), mlir::Operation::hasAttr(), mlir::Type::isa(), mlir::OperationState::location, mlir::success(), and vectorType().
Referenced by verify().
verifyVectorShapeCast()
static LogicalResult verifyVectorShapeCast (Operation * op, VectorType sourceVectorType, VectorType resultVectorType) static
Definition at line 3124 of file VectorOps.cpp.
References mlir::Operation::emitOpError(), isValidShapeCast(), and mlir::success().
Referenced by verify().
Variable Documentation
combiningKindsList
constexpr const CombiningKind combiningKindsList[] static
Initial value:
= {
    CombiningKind::ADD,
    CombiningKind::MUL,
    CombiningKind::MIN,
    CombiningKind::MAX,
    CombiningKind::AND,
    CombiningKind::OR,
    CombiningKind::XOR,
}
Definition at line 139 of file VectorOps.cpp.
Referenced by mlir::vector::CombiningKindAttr::print().