MLIR: lib/IR/Verifier.cpp File Reference
Verifier.cpp File Reference
#include "mlir/IR/Verifier.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/Dialect.h"
#include "mlir/IR/Dominance.h"
#include "mlir/IR/Operation.h"
#include "mlir/IR/RegionKindInterface.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/Support/FormatVariadic.h"
#include "llvm/Support/PrettyStackTrace.h"
#include "llvm/Support/Regex.h"
Functions
static bool mayNotHaveTerminator (Block *block)
Returns true if this block may be valid without terminator.
static void attachNoteForOperandDefinition (InFlightDiagnostic &diag, Operation &op, Value operand)
Attach a note to an in-flight diagnostic that provide more information about where an op operand is defined.
Function Documentation
attachNoteForOperandDefinition()
static void attachNoteForOperandDefinition (InFlightDiagnostic & diag, Operation & op, Value operand) static
Attach a note to an in-flight diagnostic that provide more information about where an op operand is defined.
Definition at line 252 of file Verifier.cpp.
References mlir::InFlightDiagnostic::attachNote(), mlir::Region::begin(), mlir::Value::cast(), diag(), mlir::Operation::emitError(), mlir::failed(), mlir::failure(), mlir::Operation::getBlock(), mlir::Operation::getContext(), mlir::Value::getDefiningOp(), mlir::Operation::getLoc(), mlir::Operation::getNumOperands(), mlir::Operation::getOperand(), mlir::Block::getParent(), mlir::Block::getParentOp(), mlir::Operation::getRegions(), mlir::Region::isProperAncestor(), and mlir::success().
mayNotHaveTerminator()
static bool mayNotHaveTerminator (Block * block) static
Returns true if this block may be valid without terminator.
That is if:
it does not have a parent region.
Or the parent region have a single block and:
This region does not have a parent op.
Or the parent op is unregistered.
Or the parent op has the NoTerminator trait.
Definition at line 122 of file Verifier.cpp.
References mlir::Dialect::allowsUnknownOperations(), mlir::Block::back(), mlir::Region::begin(), mlir::Block::begin(), mlir::emitError(), mlir::Operation::emitError(), mlir::Operation::emitOpError(), mlir::Region::empty(), mlir::Block::empty(), mlir::Region::end(), mlir::Block::end(), mlir::failed(), mlir::failure(), mlir::OperationName::getAbstractOperation(), mlir::Block::getArguments(), mlir::Operation::getAttrs(), mlir::OperationName::getDialect(), mlir::Operation::getName(), mlir::Dialect::getNamespace(), mlir::Operation::getNumRegions(), mlir::Operation::getNumSuccessors(), mlir::Operation::getOperands(), mlir::Block::getParent(), mlir::Block::getParentOp(), mlir::Operation::getRegion(), mlir::Block::getSuccessors(), mlir::Graph, mlir::Operation::isRegistered(), mlir::Operation::mightHaveTrait(), mlir::SSACFG, and mlir::success().